package EuchreCodingProject;

public class Partnership extends Member {
    private Member member1;
    private Member member2;
    private int partnershipID;

    // Constructor for new partnership
    public Partnership(String name, Member member1, Member member2) {
        super(name, null);
        this.member1 = member1;
        this.member2 = member2; 
        this.partnershipID = getUserID(); // partnership ID generated by super class constructor as userID
    }

    public Member getMember1() {return member1;}
    public Member getMember2() {return member2;}
    public int getPartnershipID() {return partnershipID;}
    
}
